### PR TITLE
9Anime: Fix

### LINKED ISSUE #697: [Bug] <9anime>: <some animes load whilst others dont>
## Device information
- Tachiyomi version: App version: 0.12.3.7-4514 
- Android version: MIUI 13

## Source information
- Name: 9anime
- Extension version: 12.8

## Steps to reproduce
1. Find an anime to watch
2. Load an episode of the anime

### Expected behavior
All animes should load and work without error
Screenshot_2022-07-26-13-01-53-766_xyz jmir tachiyomi mi debug

### Actual behavior
I'm able to watch some animes aka ongoing animes and unable to watch completed anime
Screenshot_2022-07-26-13-02-08-604_xyz jmir tachiyomi mi debug

## Other details
Checked crash logs, nothing reported in there
Uninstalled the extension and reinstalled it and error continues to happen

### LINKED ISSUE #713: [Bug] <9anime>: <downloading failed>
9anime give error on downloading ep

Uploading Screenrecorder-2022-07-30-19-04-58-283.mp4…

And
Screenshot_2022-07-30-19-12-34-499_com miui gallery

### LINKED ISSUE #733: [Bug] <9anime>:<both download and failed script flailed>
Screenshot_20220805-162321_Aniyomi
Screenshot_20220805-162338_Aniyomi

### LINKED ISSUE #761: 9anime Keeps Uninstalling Automatically
### Source information and language

9Anime 13.21 (English)

### Steps to reproduce

1. Install 9Anime extension from the browse section.
2. Close Aniyomi app from the memory.
3. Reopen the app.
4. 9Anime automatically gets uninstalled.

### Expected behavior

9Anime extension should be present in the anime extensions list in the browse section.

### Actual behavior

9Anime extension is not present in the anime extensions list and is automatically uninstalled.

### Aniyomi version

r4514

### Android version

12.1

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #771: [Extension Issue] <9anime>: <Always uninstalls itself>
I'm confused about the 9anime extension. I installed it a long time ago and recently I went to watch and realised it had been uninstalled. So I installed it again but then when I reload the app itself the extension is uninstalled again.

### LINKED ISSUE #781: 9anime uninstalling and error
### Source information and language

9anime 13.21 (en)

### Steps to reproduce

1. open the app
2. go to anime
3. update anime or click to watch an episode

### Expected behavior

should play the  episode 

### Actual behavior

it give me an Expected start of object '{', but had 'EOF' instead orror when refreshed anime or i click to watch an anime

### Aniyomi version

Aniyomi v0.12.3.7

### Android version

android 7

### Other details

the extension also uninstalls itself after some time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #825: 9anime does not work still, after new update
### Source information and language

9anime

### Steps to reproduce

Click on any stream, and it just says "bruh"

### Expected behavior

Play the stream

### Actual behavior

spats out "bruh"

### Aniyomi version

0.12.3.8

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1078: 9anime not working
### Source information and language

9anime v13.22 English

### Steps to reproduce

1. go to 9anime extension to browse
2. select any anime
3. error occurs

### Expected behavior

anime episodes should be displayed

### Actual behavior

no episode is shown after the error

### Aniyomi version

App version: 0.14.2.0-5846 (standard, aa69f47a1, 93, 2022-11-15T10:50Z)

### Android version

Android version: 11 (SDK 30) Android build ID: lineage_hlte-userdebug 11 RQ3A.211001.001 2a6e556b0e Device brand: samsung Device manufacturer: samsung Device name: hlte Device model: SM-N9005 Device product name: hlte

### Other details

Screenshot_20221216-015559_Aniyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1110: New 9anime Extension
### Source name

9anime

### Source link

https://9anime.to/

### Language

English, Japanese, etc.

### Other details

There's a bunch of 9anime websites on Google search which I don't trust them to use as they would personally identify any users through advertisments easily besides this website that has been verified as the real website source for you guys to implement as an extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://aniyomi.jmir.xyz/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/jmir1/aniyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by LuftVerbot**
9Anime should work now. Only downside would be that the loading times for the episode-list depends on the length so if you want to watch one piece I would recommend to use a other extension.

Closes #1110
Closes #1078 
Closes #825 
Closes #781 
Closes #771 
Closes #761
Closes #733 
Closes #713
Closes #697

### CODE REVIEW

File: src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt [hunk 1]
```diff
@@ -68,67 +66,89 @@ class NineAnime : ConfigurableAnimeSource, ParsedAnimeHttpSource() {
...
+        return GET("$baseUrl/ajax/episode/list/$id?vrf=$vrf", headers = Headers.headersOf("url", anime.url))
     }
 
     override fun episodeListParse(response: Response): List<SEpisode> {
+        val animeUrl = response.request.header("url").toString()
         val responseObject = json.decodeFromString<JsonObject>(response.body!!.string())
         val document = Jsoup.parse(JSONUtil.unescape(responseObject["result"]!!.jsonPrimitive.content))
-        return document.select(episodeListSelector()).map(::episodeFromElement).reversed()
+        val episodeElements = document.select(episodeListSelector())
+        return episodeElements.map { episodeFromElements(it, animeUrl) }
```
Comment (jmir1) [inline src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt:79]: maybe try to use something like `parallelMap` like in the zoro extension in order to make it faster...
code: https://github.com/jmir1/aniyomi-extensions/blob/master/src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/Zoro.kt#L408-L411

**Review by jmir1 — CHANGES_REQUESTED** [review]

File: src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt (hunk 1 above)
Comment (LuftVerbot) [reply src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt:79]: it's so slow because of the webview or is this helping. Because I'm not sure what this does

Comment (jmir1) [reply src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt:79]: this will make run the webview interceptor for all episodes at the same time, making it faster (in theory).
just try using parallelMap instead of map and see if it works...

File: src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt [hunk 2]
```diff
@@ -234,8 +258,8 @@ class NineAnime : ConfigurableAnimeSource, ParsedAnimeHttpSource() {
         val domainPref = ListPreference(screen.context).apply {
             key = "preferred_domain"
             title = "Preferred domain (requires app restart)"
-            entries = arrayOf("9anime.to", "9anime.id", "9anime.pl")
```
[the remark this answers is not in the document]
Comment (LuftVerbot) [reply src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt:237]: 9anime.id just goes to 9anime.gs so I leave it

[the remark this answers is not in the document]
Comment (LuftVerbot) [reply src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/NineAnime.kt:237]: other one is added again

**Review by jmir1 — APPROVED** [review]
